export const ERROR_CODES = {
  COMMON: {
    INTERNAL_SERVER_ERROR: 'COMMON.INTERNAL_SERVER_ERROR',
    EMPTY_RESULT: 'COMMON.EMPTY_RESULT',
    UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
    FORBIDDEN: 'COMMON.FORBIDDEN',
    BAD_REQUEST: 'COMMON.BAD_REQUEST',
  },
  LOG: {
    NOT_FOUND: 'LOG.NOT_FOUND',
    LIST_EMPTY: 'LOG.LIST_EMPTY',
    CREATE_FAILED: 'LOG.CREATE_FAILED',
    DELETE_FAILED: 'LOG.DELETE_FAILED',
    MISSING_ID: 'LOG.MISSING_ID',
  },
  PLACE: {
    NOT_FOUND: 'PLACE.NOT_FOUND',
    LIST_EMPTY: 'PLACE.LIST_EMPTY',
    CREATE_FAILED: 'PLACE.CREATE_FAILED',
    DELETE_FAILED: 'PLACE.DELETE_FAILED',
  },
  FOLLOW: {
    NOT_FOUND: 'FOLLOW.NOT_FOUND',
    LIST_EMPTY: 'FOLLOW.LIST_EMPTY',
    CREATE_FAILED: 'FOLLOW.CREATE_FAILED',
    DELETE_FAILED: 'FOLLOW.DELETE_FAILED',
  },
  USER: {
    NOT_FOUND: 'USER.NOT_FOUND',
    DELETE_FAILED: 'USER.DELETE_FAILED',
  },
  SEARCH: {
    FAILED: 'SEARCH.FAILED',
    EMPTY: 'SEARCH.EMPTY',
  },
};
