export const ERROR_CODES = {
  COMMON: {
    INTERNAL_SERVER_ERROR: 'COMMON.INTERNAL_SERVER_ERROR',
    EMPTY_RESULT: 'COMMON.EMPTY_RESULT',
    UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
    FORBIDDEN: 'COMMON.FORBIDDEN',
    BAD_REQUEST: 'COMMON.BAD_REQUEST',
    COORDINATES_REQUIRED: 'COMMON.COORDINATES_REQUIRED', // 위도/경도 누락
    EXTERNAL_API_FAILED: 'COMMON.EXTERNAL_API_FAILED', // 외부 API 요청 실패
    INVALID_RESPONSE: 'COMMON.INVALID_RESPONSE', // 응답 데이터 포맷 이상
  },
  LOG: {
    NOT_FOUND: 'LOG.NOT_FOUND',
    LIST_EMPTY: 'LOG.LIST_EMPTY',
    CREATE_FAILED: 'LOG.CREATE_FAILED',
    DELETE_FAILED: 'LOG.DELETE_FAILED',
    MISSING_ID: 'LOG.MISSING_ID',
  },
  PLACE: {
    NOT_FOUND: 'PLACE.NOT_FOUND',
    LIST_EMPTY: 'PLACE.LIST_EMPTY',
    CREATE_FAILED: 'PLACE.CREATE_FAILED',
    DELETE_FAILED: 'PLACE.DELETE_FAILED',
    REVERSE_GEOCODE_FAILED: 'PLACE.REVERSE_GEOCODE_FAILED',
    NO_ADDRESS_FOUND: 'PLACE.NO_ADDRESS_FOUND',
  },
  FOLLOW: {
    NOT_FOUND: 'FOLLOW.NOT_FOUND',
    LIST_EMPTY: 'FOLLOW.LIST_EMPTY',
    CREATE_FAILED: 'FOLLOW.CREATE_FAILED',
    DELETE_FAILED: 'FOLLOW.DELETE_FAILED',
  },
  USER: {
    NOT_FOUND: 'USER.NOT_FOUND',
    DELETE_FAILED: 'USER.DELETE_FAILED',
  },
  SEARCH: {
    FAILED: 'SEARCH.FAILED',
    EMPTY: 'SEARCH.EMPTY',
  },
};
