import type { Metadata } from 'next';
import { Prompt } from 'next/font/google';
import localFont from 'next/font/local';
import '../styles/globals.css';

const prompt = Prompt({
  subsets: ['latin'],
  weight: '700',
  display: 'swap',
  variable: '--font-prompt',
});

const untitled = localFont({
  src: [
    {
      path: './assets/fonts/untitled/test-untitled-sans-light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './assets/fonts/untitled/test-untitled-sans-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/untitled/test-untitled-sans-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './assets/fonts/untitled/test-untitled-sans-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './assets/fonts/untitled/test-untitled-sans-black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-untitled',
  display: 'swap',
});

const pretendard = localFont({
  src: './assets/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  style: 'normal',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Spoteditor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.variable} ${untitled.variable} ${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
